module controllertop_tb;
logic clk = 0;
logic n_rst;
logic start;
logic [15:0] HLBrdata;
logic SPI_dv;
logic [31:0] SPI_reg;
logic Done;
logic MAC_s;
logic MAC_l;
logic [31:0] MAC_in;
logic HLBren;
logic HLBincr;
logic HLBwen;
logic OLBincr;
logic OLBwen;
logic nxtpckt;
logic ARG_s;